DB_HOST : "34.77.113.111"
DB_USER : "root"
DB_PASSWORD: "FhFdcE9L7pM83sck"
DB: "ecowallet"
OPERATION: "DEVELOPMENT"
SECRET_KEY: "!@#$$%^"
MAIL_USER: "baggelisfoufikos@gmail.com"
MAIL_PASS: "ipollute1975"
BASIC_AUTH: 'iPolluteHiddenPassword#901'