DB_HOST : "34.77.113.111"
DB_USER : "user"
DB_PASSWORD: "rbr@s#,[yX]3L9t!"
DB: "ecowallet"
OPERATION: "PRODUCTION"
SECRET_KEY: "!@#$$%^"
MAIL_USER: "baggelisfoufikos@gmail.com"
MAIL_PASS: "ipollute1975"
BASIC_AUTH: 'iPolluteHiddenPassword#901'
HTML_TEMPLATE: 'index.html'